name: Update Konjak Prices

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  watch:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Deno
      uses: denoland/setup-deno@v1
      with:
        deno-version: v2.x

    - name: Run Konjak Prices
      run: deno run --allow-all index.ts

    - name: Add & Commit
      uses: EndBug/add-and-commit@v9
      with:
        message: "Update from GitHub Actions"
        add: "prices.jsonl"
